const STATUS_CONSULTA = Object.freeze({
  AGUARDANDO: 'aguardando',
  CONFIRMADO: 'confirmado',
  ATENDIDO: 'atendido',
  CANCELADO: 'cancelado',
  FALTA: 'falta'
});

const PRIORIDADE_CONSULTA = Object.freeze({
  NORMAL: 'normal',
  IDOSO: 'idoso',
  PCD: 'pcd',
  GESTANTE: 'gestante'
});

const STATUS_ATIVOS_CONSULTA = [STATUS_CONSULTA.AGUARDANDO, STATUS_CONSULTA.CONFIRMADO];

const TRANSICOES_STATUS_CONSULTA = Object.freeze({
  [STATUS_CONSULTA.AGUARDANDO]: [STATUS_CONSULTA.CONFIRMADO, STATUS_CONSULTA.CANCELADO],
  [STATUS_CONSULTA.CONFIRMADO]: [STATUS_CONSULTA.ATENDIDO, STATUS_CONSULTA.CANCELADO, STATUS_CONSULTA.FALTA],
  [STATUS_CONSULTA.CANCELADO]: [],
  [STATUS_CONSULTA.ATENDIDO]: [],
  [STATUS_CONSULTA.FALTA]: []
});

module.exports = {
  STATUS_CONSULTA,
  PRIORIDADE_CONSULTA,
  STATUS_ATIVOS_CONSULTA,
  TRANSICOES_STATUS_CONSULTA
};
